from odoo import fields, models

class ResCompany(models.Model):
    _inherit = 'res.company'
    initiating_party_issuer = fields.Char(size=35, help="This will be used as the 'Initiating Party Issuer' in the PAIN files generated by Odoo.")
    initiating_party_identifier = fields.Char(size=35, help="This will be used as the 'Initiating Party Identifier' in the PAIN files generated by Odoo.")
    initiating_party_scheme = fields.Char(size=35, help="This will be used as the 'Initiating Party Scheme Name' in the PAIN files generated by Odoo.")
